import { Resource, Notice } from './types';

export const notices: Notice[] = [
  {
    id: '1',
    title: 'Welcome to Tejashwi 23 Official Website',
    content: 'This portal will be used for sharing all class lectures, reference books, and important batch announcements. Save this link for future reference!',
    date: '2026-09-03',
    isImportant: true,
  },
  {
    id: '2',
    title: 'Term Exam Starting Soon',
    content: 'The Term Examination will officially start from 13th September. Please prepare accordingly.',
    date: '2026-09-03',
    isImportant: true,
  },
  {
    id: '3',
    title: 'Complete Integrated Teaching Assignment',
    content: 'Please ensure to complete your integrated teaching assignment before the term exam begins.',
    date: '2026-09-03',
    isImportant: true,
  }
];

export const resources: Resource[] = [
  // BMDC Curriculums (Kept outside subfolders at the subject level)
  {
    id: 'curriculum-anatomy',
    title: 'Curriculum',
    description: 'Official Bangladesh Medical and Dental Council (BMDC) curriculum for 1st Phase MBBS Anatomy.',
    date: '2026-09-03',
    type: 'book',
    fileUrl: 'https://www.bmdc.org.bd/docs/curriculum/2021/3.Anatomy.pdf',
    phase: '1st Phase',
    subject: 'Anatomy',
    category: 'Curriculum'
  },
  {
    id: 'curriculum-physiology',
    title: 'Curriculum',
    description: 'Official Bangladesh Medical and Dental Council (BMDC) curriculum for 1st Phase MBBS Physiology.',
    date: '2026-09-03',
    type: 'book',
    fileUrl: 'https://www.bmdc.org.bd/docs/curriculum/2021/4.Physiology.pdf',
    phase: '1st Phase',
    subject: 'Physiology',
    category: 'Curriculum'
  },
  {
    id: 'curriculum-biochemistry',
    title: 'Curriculum',
    description: 'Official Bangladesh Medical and Dental Council (BMDC) curriculum for 1st Phase MBBS Biochemistry.',
    date: '2026-09-03',
    type: 'book',
    fileUrl: 'https://www.bmdc.org.bd/docs/curriculum/2021/5.Biochemistry.pdf',
    phase: '1st Phase',
    subject: 'Biochemistry',
    category: 'Curriculum'
  },

  // Standard Textbooks for 1st Phase
  {
    id: 'book-bd-chaurasia-anatomy',
    title: "BD Chaurasia's Human Anatomy (Regional & Applied)",
    description: 'Gold standard anatomy textbook for gross anatomy, osteology and clinical correlations.',
    date: '2026-09-03',
    type: 'book',
    fileUrl: 'https://www.bmdc.org.bd/docs/curriculum/2021/3.Anatomy.pdf',
    phase: '1st Phase',
    subject: 'Anatomy',
    category: '05. Gross Anatomy Books'
  },
  {
    id: 'book-vishram-singh-general-anatomy',
    title: 'General Anatomy by Vishram Singh',
    description: 'Fundamental principles of general anatomy, tissues, fascia, bones, joints and anatomical terminology.',
    date: '2026-09-03',
    type: 'book',
    fileUrl: 'https://www.bmdc.org.bd/docs/curriculum/2021/3.Anatomy.pdf',
    phase: '1st Phase',
    subject: 'Anatomy',
    category: '04. General Anatomy Books'
  },
  {
    id: 'book-snell-clinical-anatomy',
    title: "Snell's Clinical Anatomy by Regions",
    description: 'Clinical anatomy orientation with surgical vignettes, surface anatomy and diagnostic correlations.',
    date: '2026-09-03',
    type: 'book',
    fileUrl: 'https://www.bmdc.org.bd/docs/curriculum/2021/3.Anatomy.pdf',
    phase: '1st Phase',
    subject: 'Anatomy',
    category: '03. Anatomy Clinical Books'
  },
  {
    id: 'book-inderbir-singh-histology',
    title: "Inderbir Singh's Textbook of Human Histology",
    description: 'Comprehensive microscopic anatomy with detailed color atlas diagrams and tissue histology slides.',
    date: '2026-09-03',
    type: 'book',
    fileUrl: 'https://www.bmdc.org.bd/docs/curriculum/2021/3.Anatomy.pdf',
    phase: '1st Phase',
    subject: 'Anatomy',
    category: '06. Histology Books'
  },
  {
    id: 'book-langman-embryology',
    title: "Langman's Medical Embryology",
    description: 'Essential human developmental anatomy, congenital anomalies, teratology and organogenesis.',
    date: '2026-09-03',
    type: 'book',
    fileUrl: 'https://www.bmdc.org.bd/docs/curriculum/2021/3.Anatomy.pdf',
    phase: '1st Phase',
    subject: 'Anatomy',
    category: '07. Embryology Books'
  },
  {
    id: 'book-netter-atlas-app',
    title: "Netter's Atlas of Human Anatomy & 3D Interactive Guide",
    description: 'World-renowned anatomical illustrations, interactive 3D digital atlas and region-by-region visual plates.',
    date: '2026-09-03',
    type: 'book',
    fileUrl: 'https://www.bmdc.org.bd/docs/curriculum/2021/3.Anatomy.pdf',
    phase: '1st Phase',
    subject: 'Anatomy',
    category: '08. Anatomy Atlas App'
  },
  {
    id: 'book-guyton-physiology',
    title: 'Guyton and Hall Textbook of Medical Physiology',
    description: 'Authoritative physiology reference covering cellular, organ system and regulatory physiology.',
    date: '2026-09-03',
    type: 'book',
    fileUrl: 'https://www.bmdc.org.bd/docs/curriculum/2021/4.Physiology.pdf',
    phase: '1st Phase',
    subject: 'Physiology',
    category: '04. Physiology Textbooks'
  },
  {
    id: 'book-ganong-physiology',
    title: "Ganong's Review of Medical Physiology",
    description: 'Concise, high-yield overview of mammalian and human medical physiology with clinical cases.',
    date: '2026-09-03',
    type: 'book',
    fileUrl: 'https://www.bmdc.org.bd/docs/curriculum/2021/4.Physiology.pdf',
    phase: '1st Phase',
    subject: 'Physiology',
    category: '04. Physiology Textbooks'
  },
  {
    id: 'book-lippincott-biochemistry',
    title: 'Lippincott Illustrated Reviews: Biochemistry',
    description: 'Essential illustrated biochemistry review with high-yield clinical vignettes and diagrams.',
    date: '2026-09-03',
    type: 'book',
    fileUrl: 'https://www.bmdc.org.bd/docs/curriculum/2021/5.Biochemistry.pdf',
    phase: '1st Phase',
    subject: 'Biochemistry',
    category: '04. Biochemistry Textbooks'
  },
  {
    id: 'book-harper-biochemistry',
    title: "Harper's Illustrated Biochemistry",
    description: 'Comprehensive medical biochemistry covering molecular biology, genetics and metabolic pathways.',
    date: '2026-09-03',
    type: 'book',
    fileUrl: 'https://www.bmdc.org.bd/docs/curriculum/2021/5.Biochemistry.pdf',
    phase: '1st Phase',
    subject: 'Biochemistry',
    category: '04. Biochemistry Textbooks'
  },

  // Study Guides & Review Books
  {
    id: 'guide-anatomy-item-ospe',
    title: 'Anatomy Card & Surface Marking Guide',
    description: 'Comprehensive high-yield card notes, viscera identification & surface marking guide.',
    date: '2026-09-03',
    type: 'book',
    fileUrl: 'https://www.bmdc.org.bd/docs/curriculum/2021/3.Anatomy.pdf',
    phase: '1st Phase',
    subject: 'Anatomy',
    category: '02. Anatomy Guide'
  },
  {
    id: 'anatomy-viva-practical-manual',
    title: 'Anatomy Cadaver Dissection & Practical Manual',
    description: 'Dissection guide, viscera spotters, osteology viva questions & OSPE station manual.',
    date: '2026-09-03',
    type: 'book',
    fileUrl: 'https://www.bmdc.org.bd/docs/curriculum/2021/3.Anatomy.pdf',
    phase: '1st Phase',
    subject: 'Anatomy',
    category: '01. Anatomy Viva & Practical'
  },
  {
    id: 'guide-physiology-viva-prep',
    title: 'Physiology Quick Review & Viva Guide',
    description: 'Rapid recall questions, flowchart summaries and clinical correlations for term exams.',
    date: '2026-09-03',
    type: 'book',
    fileUrl: 'https://www.bmdc.org.bd/docs/curriculum/2021/4.Physiology.pdf',
    phase: '1st Phase',
    subject: 'Physiology',
    category: '02. Physiology Guides'
  },
  {
    id: 'physiology-viva-practical-manual',
    title: 'Physiology Practical & OSPE Lab Manual',
    description: 'Practical procedures, blood lab tests, spirometry, ECG, nerve stimulation & viva voce questions.',
    date: '2026-09-03',
    type: 'book',
    fileUrl: 'https://www.bmdc.org.bd/docs/curriculum/2021/4.Physiology.pdf',
    phase: '1st Phase',
    subject: 'Physiology',
    category: '01. Physiology Viva, Practical'
  },
  {
    id: 'physiology-clinical-books-guide',
    title: 'Clinical Physiology & Pathophysiology Correlations',
    description: 'Diagnostic physiological principles, cardiovascular & respiratory case-based clinical problems.',
    date: '2026-09-03',
    type: 'book',
    fileUrl: 'https://www.bmdc.org.bd/docs/curriculum/2021/4.Physiology.pdf',
    phase: '1st Phase',
    subject: 'Physiology',
    category: '03. Physiology Clinical Books'
  },
  {
    id: 'guide-biochemistry-cycle-pathways',
    title: 'Biochemistry Pathways & Item Guide',
    description: 'Metabolic pathway diagrams, clinical enzymology notes, and viva item questions.',
    date: '2026-09-03',
    type: 'book',
    fileUrl: 'https://www.bmdc.org.bd/docs/curriculum/2021/5.Biochemistry.pdf',
    phase: '1st Phase',
    subject: 'Biochemistry',
    category: '02. Biochemistry Guides'
  },
  {
    id: 'biochemistry-viva-practical-manual',
    title: 'Biochemistry Viva, OSPE & Practical Manual',
    description: 'Complete lab practical procedures, viva voce Q&A, reagent tests and OSPE station guides.',
    date: '2026-09-03',
    type: 'book',
    fileUrl: 'https://www.bmdc.org.bd/docs/curriculum/2021/5.Biochemistry.pdf',
    phase: '1st Phase',
    subject: 'Biochemistry',
    category: '01. Biochemistry Viva, Practical'
  },
  {
    id: 'biochemistry-clinical-books-guide',
    title: 'Clinical Biochemistry & Diagnostic Medicine',
    description: 'Organ function tests, clinical enzymology, electrolyte disorders & diagnostic case studies.',
    date: '2026-09-03',
    type: 'book',
    fileUrl: 'https://www.bmdc.org.bd/docs/curriculum/2021/5.Biochemistry.pdf',
    phase: '1st Phase',
    subject: 'Biochemistry',
    category: '03. Biochemistry Clinical Books'
  },

  // 1st Term Card 01 Lectures
  {
    id: 'bio-t1-c1-item01',
    title: 'Item 01',
    description: 'Biochemistry 1st Term Card-01 lecture material & item study resources.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/biochem1ewmc/4',
    phase: '1st Phase',
    subject: 'Biochemistry',
    term: '1st Term',
    card: '1st Card'
  },
  {
    id: 'bio-t1-c1-item02',
    title: 'Item 02',
    description: 'Biochemistry 1st Term Card-01 lecture material & item study resources.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/biochem1ewmc/5',
    phase: '1st Phase',
    subject: 'Biochemistry',
    term: '1st Term',
    card: '1st Card'
  },
  {
    id: 'bio-t1-c1-item03',
    title: 'Item 03',
    description: 'Biochemistry 1st Term Card-01 lecture material & item study resources.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/biochem1ewmc/6',
    phase: '1st Phase',
    subject: 'Biochemistry',
    term: '1st Term',
    card: '1st Card'
  },
  {
    id: 'bio-t1-c1-item04',
    title: 'Item 04',
    description: 'Biochemistry 1st Term Card-01 lecture material & item study resources.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/biochem1ewmc/7',
    phase: '1st Phase',
    subject: 'Biochemistry',
    term: '1st Term',
    card: '1st Card'
  },
  {
    id: 'bio-t1-c1-item05',
    title: 'Item 05',
    description: 'Biochemistry 1st Term Card-01 lecture material & item study resources.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/biochem1ewmc/8',
    phase: '1st Phase',
    subject: 'Biochemistry',
    term: '1st Term',
    card: '1st Card'
  },
  {
    id: 'bio-t1-c1-item06',
    title: 'Item 06',
    description: 'Biochemistry 1st Term Card-01 lecture material & item study resources.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/biochem1ewmc/9',
    phase: '1st Phase',
    subject: 'Biochemistry',
    term: '1st Term',
    card: '1st Card'
  },
  {
    id: 'bio-t1-c1-item07',
    title: 'Item 07',
    description: 'Biochemistry 1st Term Card-01 lecture material & item study resources.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/biochem1ewmc/10',
    phase: '1st Phase',
    subject: 'Biochemistry',
    term: '1st Term',
    card: '1st Card'
  },
  {
    id: 'bio-t1-c1-item08',
    title: 'Item 08',
    description: 'Biochemistry 1st Term Card-01 lecture material & item study resources.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/biochem1ewmc/11',
    phase: '1st Phase',
    subject: 'Biochemistry',
    term: '1st Term',
    card: '1st Card'
  },
  {
    id: 'bio-t1-c1-written',
    title: 'Card written questions',
    description: 'Biochemistry 1st Term Card-01 written questions and question bank.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/biochem1ewmc/13',
    phase: '1st Phase',
    subject: 'Biochemistry',
    term: '1st Term',
    card: '1st Card'
  },
  {
    id: 'bio-t1-c1-viva',
    title: 'Card viva questions',
    description: 'Biochemistry 1st Term Card-01 viva questions and examiner high-yield topics.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/biochem1ewmc/14',
    phase: '1st Phase',
    subject: 'Biochemistry',
    term: '1st Term',
    card: '1st Card'
  },

  // 1st Term Card 02 Lectures
  {
    id: 'bio-t1-c2-item01',
    title: 'Item 01',
    description: 'Biochemistry 1st Term Card-02 lecture material & item study resources.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/biochem2ewmc/2',
    phase: '1st Phase',
    subject: 'Biochemistry',
    term: '1st Term',
    card: '2nd Card'
  },
  {
    id: 'bio-t1-c2-item02',
    title: 'Item 02',
    description: 'Biochemistry 1st Term Card-02 lecture material & item study resources.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/biochem2ewmc/3',
    phase: '1st Phase',
    subject: 'Biochemistry',
    term: '1st Term',
    card: '2nd Card'
  },
  {
    id: 'bio-t1-c2-item03',
    title: 'Item 03',
    description: 'Biochemistry 1st Term Card-02 lecture material & item study resources.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/biochem2ewmc/4',
    phase: '1st Phase',
    subject: 'Biochemistry',
    term: '1st Term',
    card: '2nd Card'
  },
  {
    id: 'bio-t1-c2-item04',
    title: 'Item 04',
    description: 'Biochemistry 1st Term Card-02 lecture material & item study resources.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/biochem2ewmc/5',
    phase: '1st Phase',
    subject: 'Biochemistry',
    term: '1st Term',
    card: '2nd Card'
  },
  {
    id: 'bio-t1-c2-item05',
    title: 'Item 05',
    description: 'Biochemistry 1st Term Card-02 lecture material & item study resources.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/biochem2ewmc/6',
    phase: '1st Phase',
    subject: 'Biochemistry',
    term: '1st Term',
    card: '2nd Card'
  },
  {
    id: 'bio-t1-c2-item06',
    title: 'Item 06',
    description: 'Biochemistry 1st Term Card-02 lecture material & item study resources.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/biochem2ewmc/7',
    phase: '1st Phase',
    subject: 'Biochemistry',
    term: '1st Term',
    card: '2nd Card'
  },
  {
    id: 'bio-t1-c2-viva',
    title: 'Card viva questions',
    description: 'Biochemistry 1st Term Card-02 viva questions and examiner high-yield topics.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/biochem2ewmc/8',
    phase: '1st Phase',
    subject: 'Biochemistry',
    term: '1st Term',
    card: '2nd Card'
  },
  {
    id: 'bio-t1-c2-written',
    title: 'Card written questions',
    description: 'Biochemistry 1st Term Card-02 written questions and question bank.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/biochem2ewmc/9',
    phase: '1st Phase',
    subject: 'Biochemistry',
    term: '1st Term',
    card: '2nd Card'
  },

  // PHYSIOLOGY - 1st Term Card 01 Lectures
  {
    id: 'phy-t1-c1-homeostasis',
    title: 'Homeostasis',
    description: 'Physiology 1st Term Card-01 lecture material & notes on Homeostasis.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/physiology1ewmc/2',
    phase: '1st Phase',
    subject: 'Physiology',
    term: '1st Term',
    card: '1st Card'
  },
  {
    id: 'phy-t1-c1-cell',
    title: 'Cell',
    description: 'Physiology 1st Term Card-01 lecture material & notes on Cell physiology.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/physiology1ewmc/3',
    phase: '1st Phase',
    subject: 'Physiology',
    term: '1st Term',
    card: '1st Card'
  },
  {
    id: 'phy-t1-c1-membrane-potential',
    title: 'Membrane potential',
    description: 'Physiology 1st Term Card-01 lecture material & notes on Resting & Action Membrane Potential.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/physiology1ewmc/4',
    phase: '1st Phase',
    subject: 'Physiology',
    term: '1st Term',
    card: '1st Card'
  },
  {
    id: 'phy-t1-c1-membrane-transport',
    title: 'Membrane transport',
    description: 'Physiology 1st Term Card-01 lecture material & notes on Membrane Transport mechanisms.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/physiology1ewmc/5',
    phase: '1st Phase',
    subject: 'Physiology',
    term: '1st Term',
    card: '1st Card'
  },
  {
    id: 'phy-t1-c1-blood',
    title: 'Blood',
    description: 'Physiology 1st Term Card-01 lecture material & notes on Blood composition & functions.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/physiology1ewmc/6',
    phase: '1st Phase',
    subject: 'Physiology',
    term: '1st Term',
    card: '1st Card'
  },
  {
    id: 'phy-t1-c1-rbc',
    title: 'RBC',
    description: 'Physiology 1st Term Card-01 lecture material & notes on Red Blood Cells & Erythropoiesis.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/physiology1ewmc/7',
    phase: '1st Phase',
    subject: 'Physiology',
    term: '1st Term',
    card: '1st Card'
  },
  {
    id: 'phy-t1-c1-wbc',
    title: 'WBC',
    description: 'Physiology 1st Term Card-01 lecture material & notes on White Blood Cells & Leukopoiesis.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/physiology1ewmc/8',
    phase: '1st Phase',
    subject: 'Physiology',
    term: '1st Term',
    card: '1st Card'
  },
  {
    id: 'phy-t1-c1-platelet',
    title: 'Platelet',
    description: 'Physiology 1st Term Card-01 lecture material & notes on Platelets & Hemostasis.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/physiology1ewmc/9',
    phase: '1st Phase',
    subject: 'Physiology',
    term: '1st Term',
    card: '1st Card'
  },
  {
    id: 'phy-t1-c1-anemia',
    title: 'Anemia',
    description: 'Physiology 1st Term Card-01 lecture material & notes on Anemia classification & pathophysiology.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/physiology1ewmc/10',
    phase: '1st Phase',
    subject: 'Physiology',
    term: '1st Term',
    card: '1st Card'
  },
  {
    id: 'phy-t1-c1-nmj',
    title: 'Neuromuscular junction',
    description: 'Physiology 1st Term Card-01 lecture material & notes on Neuromuscular Junction transmission.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/physiology1ewmc/11',
    phase: '1st Phase',
    subject: 'Physiology',
    term: '1st Term',
    card: '1st Card'
  },
  {
    id: 'phy-t1-c1-blood-grouping',
    title: 'Blood grouping',
    description: 'Physiology 1st Term Card-01 lecture material & notes on ABO & Rh Blood Grouping.',
    date: '2026-09-03',
    type: 'lecture',
    fileUrl: 'https://t.me/physiology1ewmc/12',
    phase: '1st Phase',
    subject: 'Physiology',
    term: '1st Term',
    card: '1st Card'
  },
  {
    id: 'phy-t1-c2-co-hr-pulse',
    title: 'CO, HR, PULSE',
    description: 'Physiology 1st Term Card-02 lecture material & notes on Cardiac Output, Heart Rate & Arterial Pulse.',
    date: '2026-09-04',
    type: 'lecture',
    fileUrl: 'https://t.me/physiology2ewmc/2',
    phase: '1st Phase',
    subject: 'Physiology',
    term: '1st Term',
    card: '2nd Card'
  },
  {
    id: 'phy-t1-c2-heart',
    title: 'Heart',
    description: 'Physiology 1st Term Card-02 lecture material & notes on Functional anatomy & properties of Cardiac Muscle.',
    date: '2026-09-04',
    type: 'lecture',
    fileUrl: 'https://t.me/physiology2ewmc/3',
    phase: '1st Phase',
    subject: 'Physiology',
    term: '1st Term',
    card: '2nd Card'
  },
  {
    id: 'phy-t1-c2-microcirculation',
    title: 'Microcirculation',
    description: 'Physiology 1st Term Card-02 lecture material & notes on Microcirculation, Capillary exchange & Lymphatics.',
    date: '2026-09-04',
    type: 'lecture',
    fileUrl: 'https://t.me/physiology2ewmc/4',
    phase: '1st Phase',
    subject: 'Physiology',
    term: '1st Term',
    card: '2nd Card'
  },
  {
    id: 'phy-t1-c2-cardiac-cycle',
    title: 'Cardiac cycle',
    description: 'Physiology 1st Term Card-02 lecture material & notes on Cardiac Cycle phases, pressure-volume changes & Heart sounds.',
    date: '2026-09-04',
    type: 'lecture',
    fileUrl: 'https://t.me/physiology2ewmc/5',
    phase: '1st Phase',
    subject: 'Physiology',
    term: '1st Term',
    card: '2nd Card'
  },
  {
    id: 'phy-t1-c2-co-sv-vr',
    title: 'CO, SV, VR',
    description: 'Physiology 1st Term Card-02 lecture material & notes on Cardiac Output, Stroke Volume & Venous Return regulation.',
    date: '2026-09-04',
    type: 'lecture',
    fileUrl: 'https://t.me/physiology2ewmc/6',
    phase: '1st Phase',
    subject: 'Physiology',
    term: '1st Term',
    card: '2nd Card'
  },
  {
    id: 'phy-t1-c2-cardiovascular-physiology',
    title: 'Cardiovascular physiology',
    description: 'Physiology 1st Term Card-02 comprehensive lecture notes on Cardiovascular Physiology & Hemodynamics.',
    date: '2026-09-04',
    type: 'lecture',
    fileUrl: 'https://t.me/physiology2ewmc/7',
    phase: '1st Phase',
    subject: 'Physiology',
    term: '1st Term',
    card: '2nd Card'
  },
  {
    id: 'phy-t1-c2-circulatory-adjustment',
    title: 'Circulatory adjustment',
    description: 'Physiology 1st Term Card-02 lecture material on Circulatory adjustments during exercise, posture changes & stress.',
    date: '2026-09-04',
    type: 'lecture',
    fileUrl: 'https://t.me/physiology2ewmc/8',
    phase: '1st Phase',
    subject: 'Physiology',
    term: '1st Term',
    card: '2nd Card'
  },
  {
    id: 'phy-t1-c2-heart-block',
    title: 'Heart block',
    description: 'Physiology 1st Term Card-02 lecture material & notes on Heart Block, Cardiac Arrhythmias & Conduction disorders.',
    date: '2026-09-04',
    type: 'lecture',
    fileUrl: 'https://t.me/physiology2ewmc/9',
    phase: '1st Phase',
    subject: 'Physiology',
    term: '1st Term',
    card: '2nd Card'
  }
];

